packages:
  github.com/qnhqn1/file-validator/internal/cache:
    interfaces:
      Cache:
        config:
          dir: internal/services/validator/mocks
          filename: cache.go
          outpkg: mocks
  github.com/qnhqn1/file-validator/internal/storage/pgstorage:
    interfaces:
      StorageInterface:
        config:
          dir: internal/services/validator/mocks
          filename: storage.go
          outpkg: mocks
